services:
  jekyll-site:
    build:
      context: .
      dockerfile: Dockerfile
    image: jekyll-site
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
    command: jekyll serve --host 0.0.0.0
    restart: no
